# Generated by Django 5.1.4 on 2024-12-07 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 7, 16, 1, 6, 659129, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
