# Generated by Django 5.1.4 on 2024-12-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='job_name',
            new_name='job_title',
        ),
    ]
